version: '3.8'

services:
  zookeeper:
    user: root
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    volumes:
      - ./zk-data:/var/lib/zookeeper/data
      - ./zk-log:/var/lib/zookeeper/log

  kafka:
    user: root
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9999
    volumes:
      - ./kafka-data:/var/lib/kafka/data
  fastapi_kafka:
    build: .
    hostname: fastapi_kafka
    container_name: fastapi_kafka
    command: sh -c "./wait && python main.py"
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    environment:
      - WAIT_HOSTS=kafka:29092
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
  consumer:
    build: .
    image: python:3.10
    container_name: kafka_consumer
    volumes:
      - ./consumer.py:/app/consumer.py
    depends_on:
      - kafka
    environment:
      - WAIT_HOSTS=kafka:29092
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    command: sh -c "./wait && python consumer.py"
networks:
  default:
    name: kafka-network
